package views;

import controllers.Authenticator;
import javax.swing.JOptionPane;

/**
 * Class to allow users to log in and register.
 */
public class LoginGUI extends javax.swing.JFrame {

	/**
	 * Creates new form LoginGUI
	 */
	public LoginGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		emailTextField = new javax.swing.JTextField();
		emailLabel = new javax.swing.JLabel();
		passwordLabel = new javax.swing.JLabel();
		registerButton = new javax.swing.JButton();
		loginButton = new javax.swing.JButton();
		passwordTextField = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		emailLabel.setText("Email");

		passwordLabel.setText("Password");

		registerButton.setText("Register");
		registerButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				registerButtonActionPerformed(evt);
			}
		});

		loginButton.setText("Login");
		loginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap(181, Short.MAX_VALUE)
										.addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(registerButton))
								.addGroup(layout.createSequentialGroup()
										.addGap(84, 84, 84)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(passwordLabel)
												.addComponent(emailLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(emailTextField)
												.addComponent(passwordTextField))))
						.addGap(90, 90, 90))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(93, 93, 93)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(emailLabel))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(passwordLabel)
								.addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(registerButton)
								.addComponent(loginButton))
						.addContainerGap(114, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Attempts registration, will prompt on failure or success. Clears all text
	 * fields.
	 */
	private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
		boolean validRegister = A.register(getEmail(), getPassword());
		if(validRegister){
			JOptionPane.showMessageDialog(LoginGUI.this, "Registration succesful");
		}else{
			JOptionPane.showMessageDialog(LoginGUI.this, "Something went wrong");
		}
		clearTextFields();
	}//GEN-LAST:event_registerButtonActionPerformed

	/**
	 * Attempts login, will prompt on failure or success. Clears all text fields.
	 */
	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		if(A.authenticate(getEmail(), getPassword())){
			JOptionPane.showMessageDialog(LoginGUI.this, "Login succesful");
		}else{
			JOptionPane.showMessageDialog(LoginGUI.this, "Invalid email address or password");
		}
		clearTextFields();
	}//GEN-LAST:event_loginButtonActionPerformed

	/**
	 * Clears all text fields.
	 */
	public void clearTextFields(){
		emailTextField.setText("");
		passwordTextField.setText("");
	}

	/**
	 * @return: String in email text box
	 */
	public String getEmail(){
		return emailTextField.getText();
	}

	/**
	 * @return: String in Password text box
	 */
	public String getPassword(){
		return passwordTextField.getText();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginGUI().setVisible(true);
			}
		});
	}

	private Authenticator A;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel emailLabel;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JButton loginButton;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JPasswordField passwordTextField;
	private javax.swing.JButton registerButton;
	// End of variables declaration//GEN-END:variables
}
